package com.ziyue.immodel.dao;


import com.ziyue.imentity.entity.Blacklist;

public interface BlacklistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blacklist
     *
     * @mbg.generated
     */
    int insert(Blacklist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blacklist
     *
     * @mbg.generated
     */
    int insertSelective(Blacklist record);
}