package com.ziyue.immodel.dao;


import com.ziyue.imentity.entity.Board;

public interface BoardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table board
     *
     * @mbg.generated
     */
    int insert(Board record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table board
     *
     * @mbg.generated
     */
    int insertSelective(Board record);
}