package com.ziyue.immodel.dao;


import com.ziyue.imentity.entity.Catalog;

public interface CatalogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbg.generated
     */
    int insert(Catalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbg.generated
     */
    int insertSelective(Catalog record);
}