package com.ziyue.immodel.dao;


import com.ziyue.imentity.entity.Column;

public interface ColumnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column
     *
     * @mbg.generated
     */
    int insert(Column record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column
     *
     * @mbg.generated
     */
    int insertSelective(Column record);
}