package com.ziyue.imentity.entity;

import java.io.Serializable;
import java.util.Date;

public class Blacklist implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.chat_id
     *
     * @mbg.generated
     */
    private Integer chatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.reason
     *
     * @mbg.generated
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.informer_id
     *
     * @mbg.generated
     */
    private Integer informerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.check_at
     *
     * @mbg.generated
     */
    private Date checkAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blacklist
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blacklist
     *
     * @mbg.generated
     */
    public Blacklist(Integer id, Integer type, Integer userId, Integer chatId, String reason, Integer informerId, Integer status, Date checkAt, Date createdAt, Date updatedAt) {
        this.id = id;
        this.type = type;
        this.userId = userId;
        this.chatId = chatId;
        this.reason = reason;
        this.informerId = informerId;
        this.status = status;
        this.checkAt = checkAt;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blacklist
     *
     * @mbg.generated
     */
    public Blacklist() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.id
     *
     * @return the value of blacklist.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.id
     *
     * @param id the value for blacklist.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.type
     *
     * @return the value of blacklist.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.type
     *
     * @param type the value for blacklist.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.user_id
     *
     * @return the value of blacklist.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.user_id
     *
     * @param userId the value for blacklist.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.chat_id
     *
     * @return the value of blacklist.chat_id
     *
     * @mbg.generated
     */
    public Integer getChatId() {
        return chatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.chat_id
     *
     * @param chatId the value for blacklist.chat_id
     *
     * @mbg.generated
     */
    public void setChatId(Integer chatId) {
        this.chatId = chatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.reason
     *
     * @return the value of blacklist.reason
     *
     * @mbg.generated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.reason
     *
     * @param reason the value for blacklist.reason
     *
     * @mbg.generated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.informer_id
     *
     * @return the value of blacklist.informer_id
     *
     * @mbg.generated
     */
    public Integer getInformerId() {
        return informerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.informer_id
     *
     * @param informerId the value for blacklist.informer_id
     *
     * @mbg.generated
     */
    public void setInformerId(Integer informerId) {
        this.informerId = informerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.status
     *
     * @return the value of blacklist.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.status
     *
     * @param status the value for blacklist.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.check_at
     *
     * @return the value of blacklist.check_at
     *
     * @mbg.generated
     */
    public Date getCheckAt() {
        return checkAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.check_at
     *
     * @param checkAt the value for blacklist.check_at
     *
     * @mbg.generated
     */
    public void setCheckAt(Date checkAt) {
        this.checkAt = checkAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.created_at
     *
     * @return the value of blacklist.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.created_at
     *
     * @param createdAt the value for blacklist.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.updated_at
     *
     * @return the value of blacklist.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.updated_at
     *
     * @param updatedAt the value for blacklist.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}