package com.ziyue.imentity.entity;

import java.io.Serializable;
import java.util.Date;

public class Blog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.board_id
     *
     * @mbg.generated
     */
    private Integer boardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.board
     *
     * @mbg.generated
     */
    private String board;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.column_id
     *
     * @mbg.generated
     */
    private Integer columnId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.catalog_id
     *
     * @mbg.generated
     */
    private Integer catalogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.second_catalog
     *
     * @mbg.generated
     */
    private String secondCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.cont_markdown
     *
     * @mbg.generated
     */
    private String contMarkdown;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.cont_html
     *
     * @mbg.generated
     */
    private String contHtml;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.cont
     *
     * @mbg.generated
     */
    private String cont;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.update_at
     *
     * @mbg.generated
     */
    private Date updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blog
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated
     */
    public Blog(Integer id, Integer boardId, String board, Integer columnId, Integer catalogId, String secondCatalog, String title, Integer userId, String contMarkdown, String contHtml, String cont, Date createdAt, Date updateAt) {
        this.id = id;
        this.boardId = boardId;
        this.board = board;
        this.columnId = columnId;
        this.catalogId = catalogId;
        this.secondCatalog = secondCatalog;
        this.title = title;
        this.userId = userId;
        this.contMarkdown = contMarkdown;
        this.contHtml = contHtml;
        this.cont = cont;
        this.createdAt = createdAt;
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbg.generated
     */
    public Blog() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.id
     *
     * @return the value of blog.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.id
     *
     * @param id the value for blog.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.board_id
     *
     * @return the value of blog.board_id
     *
     * @mbg.generated
     */
    public Integer getBoardId() {
        return boardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.board_id
     *
     * @param boardId the value for blog.board_id
     *
     * @mbg.generated
     */
    public void setBoardId(Integer boardId) {
        this.boardId = boardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.board
     *
     * @return the value of blog.board
     *
     * @mbg.generated
     */
    public String getBoard() {
        return board;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.board
     *
     * @param board the value for blog.board
     *
     * @mbg.generated
     */
    public void setBoard(String board) {
        this.board = board == null ? null : board.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.column_id
     *
     * @return the value of blog.column_id
     *
     * @mbg.generated
     */
    public Integer getColumnId() {
        return columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.column_id
     *
     * @param columnId the value for blog.column_id
     *
     * @mbg.generated
     */
    public void setColumnId(Integer columnId) {
        this.columnId = columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.catalog_id
     *
     * @return the value of blog.catalog_id
     *
     * @mbg.generated
     */
    public Integer getCatalogId() {
        return catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.catalog_id
     *
     * @param catalogId the value for blog.catalog_id
     *
     * @mbg.generated
     */
    public void setCatalogId(Integer catalogId) {
        this.catalogId = catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.second_catalog
     *
     * @return the value of blog.second_catalog
     *
     * @mbg.generated
     */
    public String getSecondCatalog() {
        return secondCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.second_catalog
     *
     * @param secondCatalog the value for blog.second_catalog
     *
     * @mbg.generated
     */
    public void setSecondCatalog(String secondCatalog) {
        this.secondCatalog = secondCatalog == null ? null : secondCatalog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.title
     *
     * @return the value of blog.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.title
     *
     * @param title the value for blog.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.user_id
     *
     * @return the value of blog.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.user_id
     *
     * @param userId the value for blog.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.cont_markdown
     *
     * @return the value of blog.cont_markdown
     *
     * @mbg.generated
     */
    public String getContMarkdown() {
        return contMarkdown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.cont_markdown
     *
     * @param contMarkdown the value for blog.cont_markdown
     *
     * @mbg.generated
     */
    public void setContMarkdown(String contMarkdown) {
        this.contMarkdown = contMarkdown == null ? null : contMarkdown.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.cont_html
     *
     * @return the value of blog.cont_html
     *
     * @mbg.generated
     */
    public String getContHtml() {
        return contHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.cont_html
     *
     * @param contHtml the value for blog.cont_html
     *
     * @mbg.generated
     */
    public void setContHtml(String contHtml) {
        this.contHtml = contHtml == null ? null : contHtml.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.cont
     *
     * @return the value of blog.cont
     *
     * @mbg.generated
     */
    public String getCont() {
        return cont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.cont
     *
     * @param cont the value for blog.cont
     *
     * @mbg.generated
     */
    public void setCont(String cont) {
        this.cont = cont == null ? null : cont.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.created_at
     *
     * @return the value of blog.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.created_at
     *
     * @param createdAt the value for blog.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.update_at
     *
     * @return the value of blog.update_at
     *
     * @mbg.generated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.update_at
     *
     * @param updateAt the value for blog.update_at
     *
     * @mbg.generated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}