package com.ziyue.imentity.entity;

import java.io.Serializable;
import java.util.Date;

public class Board implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column board.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column board.section_id
     *
     * @mbg.generated
     */
    private Integer sectionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column board.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column board.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column board.t_order
     *
     * @mbg.generated
     */
    private Integer tOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column board.pic
     *
     * @mbg.generated
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column board.create_at
     *
     * @mbg.generated
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table board
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table board
     *
     * @mbg.generated
     */
    public Board(Integer id, Integer sectionId, String title, String content, Integer tOrder, String pic, Date createAt) {
        this.id = id;
        this.sectionId = sectionId;
        this.title = title;
        this.content = content;
        this.tOrder = tOrder;
        this.pic = pic;
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table board
     *
     * @mbg.generated
     */
    public Board() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column board.id
     *
     * @return the value of board.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column board.id
     *
     * @param id the value for board.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column board.section_id
     *
     * @return the value of board.section_id
     *
     * @mbg.generated
     */
    public Integer getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column board.section_id
     *
     * @param sectionId the value for board.section_id
     *
     * @mbg.generated
     */
    public void setSectionId(Integer sectionId) {
        this.sectionId = sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column board.title
     *
     * @return the value of board.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column board.title
     *
     * @param title the value for board.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column board.content
     *
     * @return the value of board.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column board.content
     *
     * @param content the value for board.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column board.t_order
     *
     * @return the value of board.t_order
     *
     * @mbg.generated
     */
    public Integer gettOrder() {
        return tOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column board.t_order
     *
     * @param tOrder the value for board.t_order
     *
     * @mbg.generated
     */
    public void settOrder(Integer tOrder) {
        this.tOrder = tOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column board.pic
     *
     * @return the value of board.pic
     *
     * @mbg.generated
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column board.pic
     *
     * @param pic the value for board.pic
     *
     * @mbg.generated
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column board.create_at
     *
     * @return the value of board.create_at
     *
     * @mbg.generated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column board.create_at
     *
     * @param createAt the value for board.create_at
     *
     * @mbg.generated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }
}