package com.ziyue.imentity.entity;

import java.io.Serializable;
import java.util.Date;

public class Chat implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.section_id
     *
     * @mbg.generated
     */
    private Integer sectionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.board_id
     *
     * @mbg.generated
     */
    private Integer boardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.ico
     *
     * @mbg.generated
     */
    private String ico;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.good
     *
     * @mbg.generated
     */
    private String good;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.paytype
     *
     * @mbg.generated
     */
    private Integer paytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.company
     *
     * @mbg.generated
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.mark
     *
     * @mbg.generated
     */
    private String mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.answer_rate
     *
     * @mbg.generated
     */
    private Float answerRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.timeliness
     *
     * @mbg.generated
     */
    private Float timeliness;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.create_at
     *
     * @mbg.generated
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.pass_at
     *
     * @mbg.generated
     */
    private Date passAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chat
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated
     */
    public Chat(Integer id, Integer userId, Integer sectionId, Integer boardId, String title, String ico, String good, Integer paytype, String phone, String email, String company, String mark, Float answerRate, Float timeliness, Integer status, Date createAt, Date passAt) {
        this.id = id;
        this.userId = userId;
        this.sectionId = sectionId;
        this.boardId = boardId;
        this.title = title;
        this.ico = ico;
        this.good = good;
        this.paytype = paytype;
        this.phone = phone;
        this.email = email;
        this.company = company;
        this.mark = mark;
        this.answerRate = answerRate;
        this.timeliness = timeliness;
        this.status = status;
        this.createAt = createAt;
        this.passAt = passAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated
     */
    public Chat() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.id
     *
     * @return the value of chat.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.id
     *
     * @param id the value for chat.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.user_id
     *
     * @return the value of chat.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.user_id
     *
     * @param userId the value for chat.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.section_id
     *
     * @return the value of chat.section_id
     *
     * @mbg.generated
     */
    public Integer getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.section_id
     *
     * @param sectionId the value for chat.section_id
     *
     * @mbg.generated
     */
    public void setSectionId(Integer sectionId) {
        this.sectionId = sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.board_id
     *
     * @return the value of chat.board_id
     *
     * @mbg.generated
     */
    public Integer getBoardId() {
        return boardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.board_id
     *
     * @param boardId the value for chat.board_id
     *
     * @mbg.generated
     */
    public void setBoardId(Integer boardId) {
        this.boardId = boardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.title
     *
     * @return the value of chat.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.title
     *
     * @param title the value for chat.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.ico
     *
     * @return the value of chat.ico
     *
     * @mbg.generated
     */
    public String getIco() {
        return ico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.ico
     *
     * @param ico the value for chat.ico
     *
     * @mbg.generated
     */
    public void setIco(String ico) {
        this.ico = ico == null ? null : ico.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.good
     *
     * @return the value of chat.good
     *
     * @mbg.generated
     */
    public String getGood() {
        return good;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.good
     *
     * @param good the value for chat.good
     *
     * @mbg.generated
     */
    public void setGood(String good) {
        this.good = good == null ? null : good.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.paytype
     *
     * @return the value of chat.paytype
     *
     * @mbg.generated
     */
    public Integer getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.paytype
     *
     * @param paytype the value for chat.paytype
     *
     * @mbg.generated
     */
    public void setPaytype(Integer paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.phone
     *
     * @return the value of chat.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.phone
     *
     * @param phone the value for chat.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.email
     *
     * @return the value of chat.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.email
     *
     * @param email the value for chat.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.company
     *
     * @return the value of chat.company
     *
     * @mbg.generated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.company
     *
     * @param company the value for chat.company
     *
     * @mbg.generated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.mark
     *
     * @return the value of chat.mark
     *
     * @mbg.generated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.mark
     *
     * @param mark the value for chat.mark
     *
     * @mbg.generated
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.answer_rate
     *
     * @return the value of chat.answer_rate
     *
     * @mbg.generated
     */
    public Float getAnswerRate() {
        return answerRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.answer_rate
     *
     * @param answerRate the value for chat.answer_rate
     *
     * @mbg.generated
     */
    public void setAnswerRate(Float answerRate) {
        this.answerRate = answerRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.timeliness
     *
     * @return the value of chat.timeliness
     *
     * @mbg.generated
     */
    public Float getTimeliness() {
        return timeliness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.timeliness
     *
     * @param timeliness the value for chat.timeliness
     *
     * @mbg.generated
     */
    public void setTimeliness(Float timeliness) {
        this.timeliness = timeliness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.status
     *
     * @return the value of chat.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.status
     *
     * @param status the value for chat.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.create_at
     *
     * @return the value of chat.create_at
     *
     * @mbg.generated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.create_at
     *
     * @param createAt the value for chat.create_at
     *
     * @mbg.generated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.pass_at
     *
     * @return the value of chat.pass_at
     *
     * @mbg.generated
     */
    public Date getPassAt() {
        return passAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.pass_at
     *
     * @param passAt the value for chat.pass_at
     *
     * @mbg.generated
     */
    public void setPassAt(Date passAt) {
        this.passAt = passAt;
    }
}