package com.ziyue.imentity.entity;

import java.io.Serializable;
import java.util.Date;

public class Question implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.board_id
     *
     * @mbg.generated
     */
    private Integer boardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.board
     *
     * @mbg.generated
     */
    private String board;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.reward
     *
     * @mbg.generated
     */
    private Integer reward;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.is_delete
     *
     * @mbg.generated
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.adopt_user_id
     *
     * @mbg.generated
     */
    private Integer adoptUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.adopt_answer_id
     *
     * @mbg.generated
     */
    private Integer adoptAnswerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.first_answer_at
     *
     * @mbg.generated
     */
    private Date firstAnswerAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table question
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated
     */
    public Question(Integer id, Integer userId, Integer boardId, String board, String title, Integer reward, String content, Integer status, Integer isDelete, Integer adoptUserId, Integer adoptAnswerId, Date firstAnswerAt, Date createdAt, Date updatedAt) {
        this.id = id;
        this.userId = userId;
        this.boardId = boardId;
        this.board = board;
        this.title = title;
        this.reward = reward;
        this.content = content;
        this.status = status;
        this.isDelete = isDelete;
        this.adoptUserId = adoptUserId;
        this.adoptAnswerId = adoptAnswerId;
        this.firstAnswerAt = firstAnswerAt;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated
     */
    public Question() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.id
     *
     * @return the value of question.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.id
     *
     * @param id the value for question.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.user_id
     *
     * @return the value of question.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.user_id
     *
     * @param userId the value for question.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.board_id
     *
     * @return the value of question.board_id
     *
     * @mbg.generated
     */
    public Integer getBoardId() {
        return boardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.board_id
     *
     * @param boardId the value for question.board_id
     *
     * @mbg.generated
     */
    public void setBoardId(Integer boardId) {
        this.boardId = boardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.board
     *
     * @return the value of question.board
     *
     * @mbg.generated
     */
    public String getBoard() {
        return board;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.board
     *
     * @param board the value for question.board
     *
     * @mbg.generated
     */
    public void setBoard(String board) {
        this.board = board == null ? null : board.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.title
     *
     * @return the value of question.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.title
     *
     * @param title the value for question.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.reward
     *
     * @return the value of question.reward
     *
     * @mbg.generated
     */
    public Integer getReward() {
        return reward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.reward
     *
     * @param reward the value for question.reward
     *
     * @mbg.generated
     */
    public void setReward(Integer reward) {
        this.reward = reward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.content
     *
     * @return the value of question.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.content
     *
     * @param content the value for question.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.status
     *
     * @return the value of question.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.status
     *
     * @param status the value for question.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.is_delete
     *
     * @return the value of question.is_delete
     *
     * @mbg.generated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.is_delete
     *
     * @param isDelete the value for question.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.adopt_user_id
     *
     * @return the value of question.adopt_user_id
     *
     * @mbg.generated
     */
    public Integer getAdoptUserId() {
        return adoptUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.adopt_user_id
     *
     * @param adoptUserId the value for question.adopt_user_id
     *
     * @mbg.generated
     */
    public void setAdoptUserId(Integer adoptUserId) {
        this.adoptUserId = adoptUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.adopt_answer_id
     *
     * @return the value of question.adopt_answer_id
     *
     * @mbg.generated
     */
    public Integer getAdoptAnswerId() {
        return adoptAnswerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.adopt_answer_id
     *
     * @param adoptAnswerId the value for question.adopt_answer_id
     *
     * @mbg.generated
     */
    public void setAdoptAnswerId(Integer adoptAnswerId) {
        this.adoptAnswerId = adoptAnswerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.first_answer_at
     *
     * @return the value of question.first_answer_at
     *
     * @mbg.generated
     */
    public Date getFirstAnswerAt() {
        return firstAnswerAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.first_answer_at
     *
     * @param firstAnswerAt the value for question.first_answer_at
     *
     * @mbg.generated
     */
    public void setFirstAnswerAt(Date firstAnswerAt) {
        this.firstAnswerAt = firstAnswerAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.created_at
     *
     * @return the value of question.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.created_at
     *
     * @param createdAt the value for question.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.updated_at
     *
     * @return the value of question.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.updated_at
     *
     * @param updatedAt the value for question.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}