package com.ziyue.imentity.entity;

import java.io.Serializable;
import java.util.Date;

public class Users implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.visitor
     *
     * @mbg.generated
     */
    private String visitor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.nikename
     *
     * @mbg.generated
     */
    private String nikename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.avatar
     *
     * @mbg.generated
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.school
     *
     * @mbg.generated
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.domain_id
     *
     * @mbg.generated
     */
    private Integer domainId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.domain
     *
     * @mbg.generated
     */
    private String domain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.contribution
     *
     * @mbg.generated
     */
    private Integer contribution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.has_chatroom
     *
     * @mbg.generated
     */
    private Integer hasChatroom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.coin_all
     *
     * @mbg.generated
     */
    private Integer coinAll;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.coin_freeze
     *
     * @mbg.generated
     */
    private Integer coinFreeze;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.coin_usable
     *
     * @mbg.generated
     */
    private Integer coinUsable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.is_matching
     *
     * @mbg.generated
     */
    private Integer isMatching;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.login_ip
     *
     * @mbg.generated
     */
    private String loginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.mac_addr
     *
     * @mbg.generated
     */
    private String macAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.login_at
     *
     * @mbg.generated
     */
    private Date loginAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.sign_at
     *
     * @mbg.generated
     */
    private Date signAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated
     */
    public Users(Integer id, String phone, String visitor, String password, String nikename, String avatar, String school, Integer domainId, String domain, Integer contribution, Integer hasChatroom, Integer coinAll, Integer coinFreeze, Integer coinUsable, Integer status, Integer isMatching, String loginIp, String macAddr, Date loginAt, Date signAt, Date updatedAt) {
        this.id = id;
        this.phone = phone;
        this.visitor = visitor;
        this.password = password;
        this.nikename = nikename;
        this.avatar = avatar;
        this.school = school;
        this.domainId = domainId;
        this.domain = domain;
        this.contribution = contribution;
        this.hasChatroom = hasChatroom;
        this.coinAll = coinAll;
        this.coinFreeze = coinFreeze;
        this.coinUsable = coinUsable;
        this.status = status;
        this.isMatching = isMatching;
        this.loginIp = loginIp;
        this.macAddr = macAddr;
        this.loginAt = loginAt;
        this.signAt = signAt;
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated
     */
    public Users() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id
     *
     * @return the value of users.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id
     *
     * @param id the value for users.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.phone
     *
     * @return the value of users.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.phone
     *
     * @param phone the value for users.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.visitor
     *
     * @return the value of users.visitor
     *
     * @mbg.generated
     */
    public String getVisitor() {
        return visitor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.visitor
     *
     * @param visitor the value for users.visitor
     *
     * @mbg.generated
     */
    public void setVisitor(String visitor) {
        this.visitor = visitor == null ? null : visitor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.nikename
     *
     * @return the value of users.nikename
     *
     * @mbg.generated
     */
    public String getNikename() {
        return nikename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.nikename
     *
     * @param nikename the value for users.nikename
     *
     * @mbg.generated
     */
    public void setNikename(String nikename) {
        this.nikename = nikename == null ? null : nikename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.avatar
     *
     * @return the value of users.avatar
     *
     * @mbg.generated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.avatar
     *
     * @param avatar the value for users.avatar
     *
     * @mbg.generated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.school
     *
     * @return the value of users.school
     *
     * @mbg.generated
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.school
     *
     * @param school the value for users.school
     *
     * @mbg.generated
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.domain_id
     *
     * @return the value of users.domain_id
     *
     * @mbg.generated
     */
    public Integer getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.domain_id
     *
     * @param domainId the value for users.domain_id
     *
     * @mbg.generated
     */
    public void setDomainId(Integer domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.domain
     *
     * @return the value of users.domain
     *
     * @mbg.generated
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.domain
     *
     * @param domain the value for users.domain
     *
     * @mbg.generated
     */
    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.contribution
     *
     * @return the value of users.contribution
     *
     * @mbg.generated
     */
    public Integer getContribution() {
        return contribution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.contribution
     *
     * @param contribution the value for users.contribution
     *
     * @mbg.generated
     */
    public void setContribution(Integer contribution) {
        this.contribution = contribution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.has_chatroom
     *
     * @return the value of users.has_chatroom
     *
     * @mbg.generated
     */
    public Integer getHasChatroom() {
        return hasChatroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.has_chatroom
     *
     * @param hasChatroom the value for users.has_chatroom
     *
     * @mbg.generated
     */
    public void setHasChatroom(Integer hasChatroom) {
        this.hasChatroom = hasChatroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.coin_all
     *
     * @return the value of users.coin_all
     *
     * @mbg.generated
     */
    public Integer getCoinAll() {
        return coinAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.coin_all
     *
     * @param coinAll the value for users.coin_all
     *
     * @mbg.generated
     */
    public void setCoinAll(Integer coinAll) {
        this.coinAll = coinAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.coin_freeze
     *
     * @return the value of users.coin_freeze
     *
     * @mbg.generated
     */
    public Integer getCoinFreeze() {
        return coinFreeze;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.coin_freeze
     *
     * @param coinFreeze the value for users.coin_freeze
     *
     * @mbg.generated
     */
    public void setCoinFreeze(Integer coinFreeze) {
        this.coinFreeze = coinFreeze;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.coin_usable
     *
     * @return the value of users.coin_usable
     *
     * @mbg.generated
     */
    public Integer getCoinUsable() {
        return coinUsable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.coin_usable
     *
     * @param coinUsable the value for users.coin_usable
     *
     * @mbg.generated
     */
    public void setCoinUsable(Integer coinUsable) {
        this.coinUsable = coinUsable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.status
     *
     * @return the value of users.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.status
     *
     * @param status the value for users.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.is_matching
     *
     * @return the value of users.is_matching
     *
     * @mbg.generated
     */
    public Integer getIsMatching() {
        return isMatching;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.is_matching
     *
     * @param isMatching the value for users.is_matching
     *
     * @mbg.generated
     */
    public void setIsMatching(Integer isMatching) {
        this.isMatching = isMatching;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.login_ip
     *
     * @return the value of users.login_ip
     *
     * @mbg.generated
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.login_ip
     *
     * @param loginIp the value for users.login_ip
     *
     * @mbg.generated
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp == null ? null : loginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.mac_addr
     *
     * @return the value of users.mac_addr
     *
     * @mbg.generated
     */
    public String getMacAddr() {
        return macAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.mac_addr
     *
     * @param macAddr the value for users.mac_addr
     *
     * @mbg.generated
     */
    public void setMacAddr(String macAddr) {
        this.macAddr = macAddr == null ? null : macAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.login_at
     *
     * @return the value of users.login_at
     *
     * @mbg.generated
     */
    public Date getLoginAt() {
        return loginAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.login_at
     *
     * @param loginAt the value for users.login_at
     *
     * @mbg.generated
     */
    public void setLoginAt(Date loginAt) {
        this.loginAt = loginAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.sign_at
     *
     * @return the value of users.sign_at
     *
     * @mbg.generated
     */
    public Date getSignAt() {
        return signAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.sign_at
     *
     * @param signAt the value for users.sign_at
     *
     * @mbg.generated
     */
    public void setSignAt(Date signAt) {
        this.signAt = signAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.updated_at
     *
     * @return the value of users.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.updated_at
     *
     * @param updatedAt the value for users.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}